import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  stage1Sidebar: [
    {
      type: 'category',
      label: 'Stage 1: Foundations',
      link: {
        type: 'doc',
        id: 'stage-1/intro',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stage-1',
        },
      ],
    },
  ],

  stage2Sidebar: [
    {
      type: 'category',
      label: 'Stage 2: ROS 2 & Simulation',
      link: {
        type: 'doc',
        id: 'stage-2/intro',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stage-2',
        },
      ],
    },
  ],

  stage3Sidebar: [
    {
      type: 'category',
      label: 'Stage 3: Perception & Planning',
      link: {
        type: 'doc',
        id: 'stage-3/intro',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stage-3',
        },
      ],
    },
  ],

  stage4Sidebar: [
    {
      type: 'category',
      label: 'Stage 4: AI Integration',
      link: {
        type: 'doc',
        id: 'stage-4/intro',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stage-4',
        },
      ],
    },
  ],

  stage5Sidebar: [
    {
      type: 'category',
      label: 'Stage 5: Capstone Project',
      link: {
        type: 'doc',
        id: 'stage-5/intro',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stage-5',
        },
      ],
    },
  ],
};

export default sidebars;
